[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "dv-flow-librdl"
version = "0.0.1"
dependencies = [
    "dv-flow-mgr",
    "peakrdl",
]
authors = [
    {name = "Matthew Ballance", email = "matt.ballance@gmail.com"},
]
description = "Provides dv-flow tasks for performing common SystemRDL operations via PeakRDL"
license = {file = "LICENSE"}

[project.entry-points."dv_flow.mgr"]
librdl = "dv_flow.librdl.__ext__"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"dv_flow.librdl" = ["*.yaml", "share/*.md"]

[tool.pytest.ini_options]
testpaths = ["tests/unit"]
